version: "2"
services:
    web:
        build: .
        volumes:
            - ./:/usr/src/app
            - /app/node_modules
        ports:
            - "3001:3001"  
        links:
            - db 
    db:
        image: mongo
        ports:
            - "27017:27017"

